### ISSUE TITLE
broken for the last couple of weeks

### ISSUE THREAD

**Issue by primaeval** [skandi/xbmc-addon-teleboy#16]
Hi. The addon seems to be broken at the moment. I think it's since they introduced adverts for the free option. I got Channel 4 to play once but nothing else.

**Comment by skandi** [comment]
Hi. I can not agree. I just checked five random channels, all of them worked like a charm.

**Comment by primaeval** [comment]
Thanks for checking. Was it the free subscription?

**Comment by skandi** [comment]
Yes. I do not own a "plus" account ;)

**Comment by primaeval** [comment]
Thanks. It must be something to do with my connection.
