### ISSUE TITLE
Login fails due to changes in Teleboy's login

### ISSUE THREAD

**Issue by weismw** [skandi/xbmc-addon-teleboy#20]
Hi Skandi,

First, thanks for creating this great addon for Kodi. 
I traced the issue down to resent changes in teleboys login steps. Now they send out a temporary cinergy_s when you call the login page and when you call the login_check page you receive a new cinergy_s and cinergy_auth cookie. Only at this point your are logged in.

I made the following changes to your code and everything is working now again (changes in Teleboy.py):
1) Line 27: changed TB_URL to https i.e. TB_URL = "https://www.teleboy.ch"
2) Line 45: changed cinergy_s to cinergy_auth i.e. if c.name == "cinergy_auth" : return True
3) Line 50: My addon is different from the code in your github on this line. I have: fetchHttps(TB_URL + "/watchlist") and this should be fetchHttps(TB_URL + "/login") as in your code.

With the above changes in Teleboy.py everything works again.

Cheers,
Michael

**Comment by skandi** [comment]
Hi,
Thank you for your support, I've just published an updated version of the plugin with exactly your proposed changes.
Cheers,
(sk)andi
